"""create reconciliation tables

Revision ID: 12b939dbb83f
Revises: 
Create Date: 2026-07-23 12:44:02.565281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b939dbb83f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('open', 'paid', 'overdue', 'cancelled', name='invoice_status'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_external_id'), 'invoices', ['external_id'], unique=True)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('stripe', 'paypal', 'mercury', 'crypto', name='payment_provider'), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('payer_email', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'matched', 'needs_review', 'unmatched', name='payment_status'), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=True)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('matched', 'needs_review', 'rejected', name='match_status'), nullable=False),
    sa.Column('method', sa.Enum('exact_reference', 'email_and_amount', 'name_and_amount', 'ai_assisted', 'manual', name='match_method'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'invoice_id', name='uq_reconciliation_payment_invoice')
    )
    op.create_index(op.f('ix_reconciliation_matches_invoice_id'), 'reconciliation_matches', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_payment_id'), 'reconciliation_matches', ['payment_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_status'), 'reconciliation_matches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_matches_status'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_payment_id'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_invoice_id'), table_name='reconciliation_matches')
    op.drop_table('reconciliation_matches')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_external_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
